
language: node_js
node_js:
  - 11
services:
  - docker  
before_script:
  - npm install -g dotdocker
  - dotdocker start
  - docker pull michaelconnor/zok:2Jan2019
  - cd ui && npm ci && cd ../
  - cd zkp-utils && rm -rf node_modules && npm ci && \
  - cd ../zkp && rm -rf node_modules && npm ci && \
  - travis_wait npm run setup-all && cd ../
script:
  - npm run lint
  - ./zkp-demo-test.sh
addons:
  hosts:
    - api.nightfall.docker