
language: node_js
node_js:
  - 11
services:
  - docker  
before_script:
  - npm install -g dotdocker
  - dotdocker start
  - docker pull michaelconnor/zok:2Jan2019
  - cd ui && npm ci && cd ../
  - cd zkp-utils && npm ci && cd ../
  - cd zkp && npm ci
  - travis_wait yes|npm run setup -- -i gm17/ft-mint -s
script:
  - npm run lint
  - ./zkp-demo-test.sh
addons:
  hosts:
    - api.nightfall.docker
